### Get All Locations
GET http://localhost:3000/api/locations
Content-Type: application/json

### Get Location by ID
GET http://localhost:3000/api/locations/1
Content-Type: application/json

### Create New Location
POST http://localhost:3000/api/locations
Content-Type: application/json

{
  "name": "Mystic Riverbank",
  "region": 1  // Assure-toi que l'ID 1 de la région existe dans la base de données
}

### Update Location
PUT http://localhost:3000/api/locations/1
Content-Type: application/json

{
  "name": "Ancient Ruins",
  "region": 2  // Change to a valid region ID for updating
}

### Delete Location
DELETE http://localhost:3000/api/locations/1
Content-Type: application/json
